### ISSUE TITLE
Issue - Dragon Pet Healing Breath value not being tracked

### ISSUE THREAD

**Issue by Oniji** [RaraProjects/metrics#16]
> The current pre-release and latest testing branch does not show Healing Breath contribution at all on either Healing or P.Heals columns in Parse. 
> <img width="962" height="380" alt="Image" src="https://github.com/user-attachments/assets/9c4914ad-0cdb-4350-a146-16cabf7d4baf" />
> 
> I'm on Horizon, with the following settings:
> <img width="594" height="660" alt="Image" src="https://github.com/user-attachments/assets/e26e5d61-0df5-456f-8c7b-b0cecc537845" />
> 
> Also, the amounts healed is no longer showing in the Focus section either:
> <img width="867" height="415" alt="Image" src="https://github.com/user-attachments/assets/0f7d9f9d-5c8a-4668-b181-bcd8e6d4a7d8" /> 

 _Originally posted by @Oniji in [#13](https://github.com/RaraProjects/metrics/issues/13#issuecomment-3094392326)_

**Comment by RaraProjects** [comment]
This should be fixed on the Testing branch. It's not in the pre-release yet though.

**Comment by Oniji** [comment]
> This should be fixed on the Testing branch. It's not in the pre-release yet though.

This is still not working on HorizonXI with testing branch. 

<img width="874" height="551" alt="Image" src="https://github.com/user-attachments/assets/877bce2d-74e4-4c40-a57c-256f45a17bb5" />

**Comment by RaraProjects** [comment]
Interesting. I just tried and it works on my local client. I'll have to try on the Horizon client to see if it's specific to there.

<img width="860" height="587" alt="Image" src="https://github.com/user-attachments/assets/338dcdd1-b408-458b-9c4e-5c2e98e517e5" />
